# é…ç½®è¯´æ˜
# https://yun.yunyoujun.cn/guide/

# æ”¯æŒKaTeXå’ŒMathJax
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
  plugins:
  anchors:
    level: 1
    collisionSuffix: ""

# è·³è¿‡sourceæ¸²æŸ“çš„æ–‡ä»¶
skip_render:
  - "**/*.js"

# è‡ªå®šä¹‰ä¸»é¢˜çš„ä¸»è‰²è°ƒ
colors:
  primary: "#6200ee"
  # bg: "#F5F5F5" # èƒŒæ™¯è‰²
  selection_bg: "#8e71c1" # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  # tag_start_color:
  # tag_end_color:

# æ ‡ç­¾æŒ‡å®šè‰²å½©ï¼Œé»˜è®¤è‰² #333
tags:
  Vue: "#4fc08d"
  Hexo: "#0E834D"
  CSS: "#5298d1"
  Node.js: "#026E00"
  Git: "#F14E32"
  React: "#61dafb"
  Python: "#3776ab"
  PHP: "#8892BF"
  VS Code: "#0066B8"
  JavaScript: "#F4DF4F"
  TypeScript: "#317AC6"
  Laravel: "#F4645F"

# åˆ†ç±»æŒ‡å®šè‰²å½©ï¼Œé»˜è®¤è‰² #333
categories:
  ç¬”è®°: dimgray

# head å¤´éƒ¨èµ„æº
# head:
#   css:
#     example: //example.min.css
#   js:
#     base:
#       - xxx
#     async:
#     defer:

# ç½‘ç«™å›¾æ ‡(æ”¾åœ¨sourceæ–‡ä»¶ä¸‹)
favicon: /logo.ico

# æ ‡è¯­åŠ¨ç”»
banner:
  enable: true
  title:
    - keai
    - keqing
    - Blog
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

# å…¬å‘Š
notice:
  enable: true
  content: æ­£åœ¨å»ºè®¾ä¸­ï¼Œéƒ¨åˆ†åŠŸèƒ½ä¸å¯ç”¨ï¼Œæ•¬è¯·è°…è§£ï¼ğŸ˜Š

# UI äº®æš—
# å¯é€‰ light | dark | auto | time
mode: auto

# å­—ä½“
# head:
#   css:
#     fonts: https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@900&display=swap
# font:
#   cdn:
#     enable: true
#     lib:
#       - https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@900&display=swap
#   serif:
#     family: '''Songti SC'', ''Noto Serif SC'', STZhongsong, STKaiti, KaiTi, Roboto, serif'
#     weight: 900
#   sans_serif:
#     family: '''PingFang SC'', ''Microsoft YaHei'', Roboto, Arial, sans-serif'
#     weight: 400
#   monospace:
#     family: '''Source Code Pro'', ''Courier New'', Courier, Consolas, Monaco, monospace'

# å›¾ç‰‡èƒŒæ™¯
bg_image:
  enable: true
  url: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-0-blur-30px.jpg
  # dark: # æš—è‰²èƒŒæ™¯å›¾ç‰‡é“¾æ¥ï¼Œä»…åœ¨å¼€å¯æš—è‰²æ¨¡å¼æ—¶æœ‰æ•ˆ
  # blur: 30px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦ï¼Œæ›´å»ºè®®ç”¨æˆ·é€šè¿‡å›¾åƒå¤„ç†å·¥å…·æ¥æ¨¡ç³Šå›¾ç‰‡ä½œä¸ºèƒŒæ™¯
  opacity: 0.8

# æœç´¢èƒŒæ™¯
search:
  modal: true # å¯ç”¨æ¨¡æ€æ¡†æ—¶ï¼Œæœç´¢èƒŒæ™¯å°†ä¸ºæ¨¡ç³Šåçš„ä¸‹å±‚å†…å®¹ï¼Œä¸å†ä½¿ç”¨èƒŒæ™¯å›¾ç‰‡
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-2.jpg
  dark_bg_image: xxx # æš—è‰²æ¨¡å¼ä¸‹çš„èƒŒæ™¯ï¼Œä»…åœ¨ä½ å¼€å¯æš—è‰²æ¨¡å¼æ—¶æœ‰æ•ˆ
  # placeholder: # ç´¢æ¡†æç¤ºæ–‡å­—ï¼ˆå¦‚æœä¸è®¾ç½®ï¼Œå°†è‡ªåŠ¨æ ¹æ® Hexo è¯­è¨€é…ç½®é€‰å–å¯¹åº”çš„æ–‡æœ¬ï¼‰

# éšæœºå¤šè¾¹å½¢èƒŒæ™¯
trianglify:
  enable: false
  cellSize: 75 # å¤šè¾¹å½¢ç½‘æ ¼å°ºå¯¸
  width: 800
  height: 600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]' # è°ƒè‰²ç›˜ï¼Œè¯·å‚è€ƒæ–‡æ¡£é…ç½®
  opacity: 0.5 # é€æ˜åº¦

# ç‚¹å‡»é¡µé¢çš„çƒŸèŠ±ç‰¹æ•ˆ
fireworks:
  enable: true
  colors:
    - "102, 167, 221"
    - "62, 131, 225"
    - "33, 78, 194"

# ç‚¹å‡»æ–‡ç« å›¾ç‰‡ï¼Œæ”¾å¤§é¢„è§ˆ
medium_zoom: true

# é¦–é¡µå¡ç‰‡ä¸æ–‡ç« å†…éƒ¨å›¾ç‰‡çš„æ»šåŠ¨æµ®ç°æ•ˆæœï¼Œå¯è§å®˜ç½‘ï¼Œé»˜è®¤å¼€å¯
scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

# æ›¿æ¢é¼ æ ‡å…‰æ ‡ï¼Œé»˜è®¤å…³é—­ã€‚å¼€å¯æ—¶é»˜è®¤ä½¿ç”¨ Material Design Cursors
cursor:
  enable: true
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur # é»˜è®¤å›¾æ ‡
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur # æŒ‡é’ˆï¼ˆå³é“¾æ¥çŠ¶æ€ä¸‹ï¼‰å›¾æ ‡
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur # æ–‡æœ¬ï¼ˆå³æ–‡å­—çŠ¶æ€ä¸‹ï¼‰å›¾æ ‡

# èƒŒæ™¯ä¸æ ‡ç­¾
sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: false # åœ¨ä¾§è¾¹æ æ˜¾ç¤º Hexo åŸç”Ÿæ ‡ç­¾é¡µ
    amount: 20 # æ ‡ç­¾æ•°é‡

# å¤´åƒ
avatar:
  enable: true
  url: /logo.ico
  rounded: true
  opacity: 1
  mickey_mouse: true # é»˜è®¤å…³é—­ï¼Œå¼€å¯åæ–‡ç« é¡µé¢ä¾§è¾¹æ çš„å¤´åƒå°†å‘ä¸Šç§»åŠ¨ï¼ˆè¿ªå£«å°¼è­¦å‘Šï¼‰
  status: # å¤´åƒçŠ¶æ€
    enable: false
    emoji: ğŸ˜­
    message:

# æ–‡ç« 
post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

# ä»£ç å¤åˆ¶
codeblock:
  copy_btn: true

# æ‰“èµ
reward:
  enable: false
  # icon: ri:hand-coin-line
  # comment: I'm so cute. Please give me money.
  # # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  # methods:
  #   - name: æ”¯ä»˜å®
  #     path: https://cdn.yunyoujun.cn/img/donate/alipay-qrcode.jpg
  #     color: '#00A3EE'
  #     icon: ri:alipay-line
  #     # link: https://xxxx
  #   - name: QQ æ”¯ä»˜
  #     path: https://cdn.yunyoujun.cn/img/donate/qqpay-qrcode.png
  #     color: '#12B7F5'
  #     icon: ri:qq-line
  #   - name: å¾®ä¿¡æ”¯ä»˜
  #     path: https://cdn.yunyoujun.cn/img/donate/wechatpay-qrcode.jpg
  #     color: '#2DC100'
  #     icon: ri:wechat-pay-line

# è¯„è®º
comment:
  enable: true
  tips:
    - æ¬¢è¿äº¤æµå’Œè®¨è®ºï¼Œå¦‚æ–‡ç« æœ‰é”™è¯¯æˆ–ä¸è§„èŒƒä¹‹å¤„ï¼Œè¿˜è¯·å¤šå¤šæŒ‡æ­£ï¼Œéå¸¸æ„Ÿè°¢ï¼
  candidates:
    - utterances

utterances:
  enable: true
  repo: keaikeqing/keaikeqing.github.io
  issue-term: pathname
  # label: comment
  theme: github-light
